export type BlockCategory = "Estrutura" | "Conteúdo" | "Componentes" | "Formulários";

export type SiteBlock = {
  id: string;
  label: string;
  category: BlockCategory;
  html: string;
};

export const BLOCK_CATEGORIES: BlockCategory[] = ["Estrutura", "Conteúdo", "Componentes", "Formulários"];

export const SITE_BLOCKS: SiteBlock[] = [
  { id: "section", label: "Seção", category: "Estrutura", html: '<section style="padding:72px 40px;background:#ffffff"><div style="max-width:1100px;margin:0 auto"><h2 style="font-size:42px;margin:0">Nova seção</h2><p style="color:#64748b">Descreva o objetivo desta seção.</p></div></section>' },
  { id: "container", label: "Container", category: "Estrutura", html: '<div style="max-width:1100px;margin:0 auto;padding:0 32px"><p style="margin:0;color:#64748b">Conteúdo do container</p></div>' },
  { id: "grid-2", label: "Grid · 2 colunas", category: "Estrutura", html: '<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px;padding:32px"><div style="padding:28px;background:#f8fafc">Coluna 1</div><div style="padding:28px;background:#f8fafc">Coluna 2</div></div>' },
  { id: "grid-3", label: "Grid · 3 colunas", category: "Estrutura", html: '<div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;padding:32px"><div style="padding:24px;background:#f8fafc">Coluna 1</div><div style="padding:24px;background:#f8fafc">Coluna 2</div><div style="padding:24px;background:#f8fafc">Coluna 3</div></div>' },
  { id: "grid-4", label: "Grid · 4 colunas", category: "Estrutura", html: '<div style="display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;padding:32px"><div style="padding:20px;background:#f8fafc">Coluna 1</div><div style="padding:20px;background:#f8fafc">Coluna 2</div><div style="padding:20px;background:#f8fafc">Coluna 3</div><div style="padding:20px;background:#f8fafc">Coluna 4</div></div>' },
  { id: "flex", label: "Colunas flexíveis", category: "Estrutura", html: '<div style="display:flex;gap:24px;align-items:center;padding:32px"><div style="flex:1;padding:24px;background:#f8fafc">Conteúdo flexível</div><div style="flex:1;padding:24px;background:#f8fafc">Conteúdo flexível</div></div>' },
  { id: "flex-split", label: "Flex · texto e imagem", category: "Estrutura", html: '<section style="display:flex;flex-wrap:wrap;align-items:center;gap:40px;padding:72px 40px"><div style="flex:1 1 320px"><span style="color:#2563eb;font-size:12px;font-weight:700;letter-spacing:.12em">NOVA SEÇÃO</span><h2 style="font-size:48px;line-height:1.05;letter-spacing:-.05em">Conte uma história com clareza.</h2><p style="color:#64748b;font-size:18px;line-height:1.6">Selecione cada elemento e ajuste o layout no painel de Flexbox.</p></div><div style="flex:1 1 320px;min-height:280px;background:#dbe7ff;border-radius:12px"></div></section>' },
  { id: "grid-auto", label: "Grid · cards fluidos", category: "Estrutura", html: '<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px;padding:40px"><article style="padding:28px;border:1px solid #e2e8f0;border-radius:10px"><strong>Card flexível</strong><p style="color:#64748b">Ajuste as colunas para cada dispositivo.</p></article><article style="padding:28px;border:1px solid #e2e8f0;border-radius:10px"><strong>Card flexível</strong><p style="color:#64748b">Ajuste as colunas para cada dispositivo.</p></article><article style="padding:28px;border:1px solid #e2e8f0;border-radius:10px"><strong>Card flexível</strong><p style="color:#64748b">Ajuste as colunas para cada dispositivo.</p></article></div>' },
  { id: "h1", label: "Título H1", category: "Conteúdo", html: '<h1 style="font-size:64px;line-height:1;letter-spacing:-.05em;margin:24px 0">Título principal</h1>' },
  { id: "h2", label: "Título H2", category: "Conteúdo", html: '<h2 style="font-size:46px;line-height:1.08;letter-spacing:-.04em;margin:20px 0">Título de seção</h2>' },
  { id: "h3", label: "Título H3", category: "Conteúdo", html: '<h3 style="font-size:30px;line-height:1.15;margin:18px 0">Título de conteúdo</h3>' },
  { id: "h4", label: "Título H4", category: "Conteúdo", html: '<h4 style="font-size:21px;line-height:1.25;margin:14px 0">Título complementar</h4>' },
  { id: "paragraph", label: "Parágrafo", category: "Conteúdo", html: '<p style="font-size:18px;line-height:1.65;color:#64748b;max-width:680px">Escreva um texto claro para explicar esta parte do site.</p>' },
  { id: "button", label: "Botão de ação", category: "Conteúdo", html: '<a href="#" style="display:inline-block;padding:14px 20px;background:#0f172a;color:#fff;text-decoration:none;border-radius:7px;font-weight:700">Chamada para ação</a>' },
  { id: "button-group", label: "Grupo de botões", category: "Conteúdo", html: '<div style="display:flex;flex-wrap:wrap;gap:12px"><a href="#" style="display:inline-block;padding:14px 20px;background:#0f172a;color:#fff;text-decoration:none;border-radius:7px;font-weight:700">Ação principal</a><a href="#" style="display:inline-block;padding:14px 20px;border:1px solid #cbd5e1;color:#334155;text-decoration:none;border-radius:7px;font-weight:700">Saiba mais</a></div>' },
  { id: "image", label: "Imagem", category: "Conteúdo", html: '<img src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80" alt="Imagem do projeto" style="display:block;max-width:100%;height:auto" />' },
  { id: "video", label: "Vídeo embed", category: "Conteúdo", html: '<div style="position:relative;aspect-ratio:16/9;background:#0f172a;color:#fff;display:grid;place-items:center;border-radius:10px"><span>Adicione a URL do vídeo YouTube ou Vimeo no código embed</span></div>' },
  { id: "icon", label: "Ícone", category: "Conteúdo", html: '<span aria-label="Ícone" style="display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;border-radius:50%;background:#e2e8f0;font-size:22px">✦</span>' },
  { id: "header", label: "Header com menu", category: "Componentes", html: '<header style="display:flex;align-items:center;justify-content:space-between;padding:20px 32px;border-bottom:1px solid #e2e8f0"><strong style="font-size:18px">Marca do cliente</strong><nav style="display:flex;gap:20px"><a href="#" style="color:#334155;text-decoration:none">Início</a><a href="#" style="color:#334155;text-decoration:none">Sobre</a><a href="#" style="color:#334155;text-decoration:none">Contato</a></nav></header>' },
  { id: "hero", label: "Hero", category: "Componentes", html: '<section style="padding:112px 40px;background:#f8fafc"><div style="max-width:1100px;margin:0 auto"><span style="color:#2563eb;font-weight:700;letter-spacing:.12em;font-size:12px">MENSAGEM PRINCIPAL</span><h1 style="max-width:760px;font-size:72px;line-height:.95;letter-spacing:-.06em;margin:24px 0">Apresente a proposta de valor.</h1><p style="max-width:560px;font-size:19px;line-height:1.6;color:#64748b">Explique com clareza por que a empresa é a escolha certa.</p><a href="#" style="display:inline-block;margin-top:18px;padding:14px 20px;background:#0f172a;color:#fff;text-decoration:none;border-radius:7px;font-weight:700">Falar com a equipe</a></div></section>' },
  { id: "service-cards", label: "Cards de serviços", category: "Componentes", html: '<section style="padding:72px 40px"><div style="max-width:1100px;margin:0 auto"><h2 style="font-size:42px;margin:0 0 28px">Serviços</h2><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px"><article style="padding:24px;border:1px solid #e2e8f0;border-radius:10px"><h3>Serviço 01</h3><p style="color:#64748b">Descreva esta solução.</p></article><article style="padding:24px;border:1px solid #e2e8f0;border-radius:10px"><h3>Serviço 02</h3><p style="color:#64748b">Descreva esta solução.</p></article><article style="padding:24px;border:1px solid #e2e8f0;border-radius:10px"><h3>Serviço 03</h3><p style="color:#64748b">Descreva esta solução.</p></article></div></div></section>' },
  { id: "social-proof", label: "Depoimentos", category: "Componentes", html: '<section style="padding:64px 40px;background:#f8fafc"><div style="max-width:760px;margin:0 auto;text-align:center"><h2 style="font-size:40px">Depoimentos</h2><p style="color:#64748b">Insira aqui somente depoimentos aprovados pela equipe e pelo cliente.</p></div></section>' },
  { id: "pricing", label: "Tabela de preços", category: "Componentes", html: '<section style="padding:72px 40px"><div style="max-width:1100px;margin:0 auto"><h2 style="font-size:42px;text-align:center">Planos e propostas</h2><div style="display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px"><article style="padding:28px;border:1px solid #e2e8f0;border-radius:10px"><h3>Essencial</h3><p>Edite os itens da proposta.</p></article><article style="padding:28px;border:2px solid #2563eb;border-radius:10px"><h3>Completo</h3><p>Edite os itens da proposta.</p></article><article style="padding:28px;border:1px solid #e2e8f0;border-radius:10px"><h3>Personalizado</h3><p>Edite os itens da proposta.</p></article></div></div></section>' },
  { id: "faq", label: "FAQ", category: "Componentes", html: '<section style="padding:72px 40px"><div style="max-width:820px;margin:0 auto"><h2 style="font-size:42px">Perguntas frequentes</h2><details style="padding:18px 0;border-bottom:1px solid #e2e8f0"><summary style="cursor:pointer;font-weight:700">Pergunta frequente</summary><p style="color:#64748b">Escreva uma resposta objetiva.</p></details><details style="padding:18px 0;border-bottom:1px solid #e2e8f0"><summary style="cursor:pointer;font-weight:700">Outra pergunta</summary><p style="color:#64748b">Escreva uma resposta objetiva.</p></details></div></section>' },
  { id: "footer", label: "Footer", category: "Componentes", html: '<footer style="padding:40px;background:#0f172a;color:#fff"><div style="max-width:1100px;margin:0 auto;display:flex;justify-content:space-between;gap:24px"><strong>Marca do cliente</strong><span style="color:#cbd5e1">Informações de contato e direitos reservados.</span></div></footer>' },
  { id: "contact-form", label: "Formulário de contato", category: "Formulários", html: '<section style="padding:72px 40px"><div style="max-width:680px;margin:0 auto"><h2 style="font-size:42px">Vamos conversar</h2><form data-vertex-lead-form data-vertex-form-id="contact" style="display:grid;gap:14px"><label>Nome<input required name="name" type="text" placeholder="Seu nome" style="display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #cbd5e1;border-radius:6px" /></label><label>E-mail<input required name="email" type="email" placeholder="voce@empresa.com" style="display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #cbd5e1;border-radius:6px" /></label><label>Telefone<input name="phone" type="tel" placeholder="(00) 00000-0000" style="display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #cbd5e1;border-radius:6px" /></label><label>Mensagem<textarea required name="message" rows="5" placeholder="Como podemos ajudar?" style="display:block;width:100%;margin-top:6px;padding:12px;border:1px solid #cbd5e1;border-radius:6px"></textarea></label><button type="submit" style="padding:14px 20px;border:0;border-radius:7px;background:#0f172a;color:#fff;font-weight:700">Enviar mensagem</button><p data-vertex-form-status aria-live="polite" style="margin:0;color:#64748b"></p></form></div></section>' },
];
